---
deployment:
 tasks:
 - export DEPLOYPATH=/home/yrprodco/transport.yrprod.com/
 - /public -R assets $DEPLOYPATH
 - /public -R css $DEPLOYPATH
 - /public -R img $DEPLOYPATH
 - /public -R js $DEPLOYPATH
 - /public -R vendor $DEPLOYPATH
 - /public .htaccess $DEPLOYPATH
 - /public robots.txt $DEPLOYPATH
 - /public web.config $DEPLOYPATH